<?php

// $Id$ drupal 4.7 compatible
function creativecommons_lite_install() {

    switch ($GLOBALS['db_type']) {
    case 'mysql':
    case 'mysqli':
	  db_query("CREATE TABLE {creativecommons_lite} (
				  id int(10) NOT NULL auto_increment,
				  nid int(10) NOT NULL default '0',
				  data text NOT NULL,
				  PRIMARY KEY  (id),
				  KEY nid (nid))
				  TYPE=MyISAM;");
	  break;
	}   
}
// eof
